services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=n8n.kironlab.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_WEBHOOK_URL=https://n8n.kironlab.com/
      - N8N_EDITOR_BASE_URL=https://n8n.kironlab.com/
      - N8N_PROXY_HOPS=1
      - N8N_SECURE_COOKIE=true
      - GENERIC_TIMEZONE=America/Mexico_City
      - TZ=America/Mexico_City
      - NODE_ENV=production
      - TELEGRAM_CHAT_ID_ROB=8782693638
      - DRY_RUN=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
      - N8N_RUNNERS_TASK_TIMEOUT=300

volumes:
  n8n_data:
    external: true
